CREATE TABLE DOU_ATOS 
(
  PUB_NAME VARCHAR2(255 BYTE) 
, URL_TITLE VARCHAR2(255 BYTE) 
, TITLE VARCHAR2(255 BYTE) 
, CONTENT CLOB 
, PUB_DATE DATE 
, UUID VARCHAR2(36 BYTE) 
, ANO VARCHAR2(4 BYTE) 
, DIA VARCHAR2(2 BYTE) 
, MES VARCHAR2(2 BYTE) 
, ID NUMBER NOT NULL 
, LABEL NUMBER
, CONSTRAINT DOU_ATOS_PK PRIMARY KEY (ID) 
) 
