CREATE SEQUENCE DOU_ATOS_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;


CREATE OR REPLACE TRIGGER "TRG_DOU_ATOS_BIR" 
BEFORE INSERT ON DOU_ATOS 
REFERENCING NEW AS NEW
FOR EACH ROW 
BEGIN
    IF :new.ID is null then
        SELECT DOU_ATOS_SEQ.nextval INTO :new.ID from dual;
    END IF;
END;
/
ALTER TRIGGER "TRG_DOU_ATOS_BIR" ENABLE;
